### ISSUE TITLE
timetracker empty

### ISSUE THREAD

**Issue by PowerChaos** [philippK-de/Collabtive#115]
hi,
when the timetracker is empty then it gives a white page
as soon i add a new input from homepage the timetracker works

i also added following code in managetimetracker.php , but it shoulnd cause that problem (anyway code is for reference ) 

    /*Custom Edit*/
    if (!empty($cleanGet["start"]) and !empty($cleanGet["end"])) {
    $track = $tracker->getProjectTrack($id, $cleanGet["usr"], $cleanGet["task"], $cleanGet["start"], $cleanGet["end"], false);
    } else {
        $track = $tracker->getProjectTrack($id, $cleanGet["usr"], $cleanGet["task"], 0, 0, false);
    }

    $totaltime = $tracker->getTotalTrackTime($track);
    $totaltime = str_replace(".", ",", $totaltime);
	/* Custom Edit*/ 

can you check this please
bug exist in commit https://github.com/philippK-de/Collabtive/commit/cba9668fc1c1a82bbdb347700fb874d99b84db5b

also mirror bug is the progress bar on project page still does not update
manageproject.php?action=showproject&id=1
says 17% but shows empty bar (on project overvieuw it shows a red bar filled for 17% )

Greets From PowerChaos

**Comment by PowerChaos** [comment]
fixed
template/standaard/project.tpl
line 57 - 61
change
                   ` <div class="status">
                    {$done}%
                    <div class="statusbar">
                        <div class="complete" id="completed" style="width:0%;"></div>
                    </div>`
to
                    `<div class="status">
                    {$done}%
                    <div class="statusbar">
                        <div class="complete" id="completed" style="width:{$done}%;"></div>
                    </div>`

**Comment by philippK-de** [comment]
filtering of the timetracker report should be fixed in 
https://github.com/philippK-de/Collabtive/commit/0eb2914bb856b558d54e0985225e35cb25336042
and
https://github.com/philippK-de/Collabtive/commit/187986368c4e2064a6ee1daecc7b4fab034b4856
https://github.com/philippK-de/Collabtive/commit/fbcc7a939316f6b85ab4ce7bae2d618b9fa08292

**Comment by PowerChaos** [comment]
bug still exist

managetimetracker.php?action=showproject&id=5
![timetrack bug](https://cloud.githubusercontent.com/assets/7650333/18957419/43c1e40c-865f-11e6-9459-ea04da90ba29.png)

shows white page if no records exist
tested on commit https://github.com/philippK-de/Collabtive/commit/01ba01083f3814cec0f550216e3c00872bb81085
